import { useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { PageHeader, SearchFilters, StatusBadge, TableAction } from '../components/Ui'
import { useData } from '../data/DataContext'
import { useAuth } from '../context/AuthContext'

const search = (row, query) => !query || Object.values(row).some(value => String(value ?? '').toLowerCase().includes(query.toLowerCase()))
const Field = ({ label, name, type = 'text', select, options = [], value, onChange, required }) => <div className="col-md-6"><label className="form-label">{label}</label>{select ? <select name={name} className="form-select" value={value} onChange={onChange} required={required}><option value="">Select {label}</option>{options.map(item => <option key={item.value ?? item} value={item.value ?? item}>{item.label ?? item}</option>)}</select> : <input name={name} type={type} className="form-control" value={value} onChange={onChange} required={required}/>}</div>
const sampleOwner = (sample, data) => sample.familyMemberId ? data.familyMembers.find(item => item.id === sample.familyMemberId)?.name || sample.person : sample.person
const technicianLab = (user, data) => user?.lab || data.technicians.find(item => item.email === user?.email || item.name === user?.name)?.lab || ''
const labCanAccessSample = (role, user, data, sample) => role !== 'Lab Technician' || sample.lab === technicianLab(user, data)

export function Samples() {
  const { role, user } = useAuth(); const { data } = useData(); const [params] = useSearchParams(); const linkedPerson = params.get('personId') || ''; const [query, setQuery] = useState(''); const [filters, setFilters] = useState({ status: '', source: '' }); const assignedLab = technicianLab(user, data); const rows = data.samples.filter(item => (!linkedPerson || item.personId === linkedPerson) && (role !== 'Lab Technician' || item.lab === assignedLab) && search(item, query) && (!filters.status || item.status === filters.status) && (!filters.source || item.source === filters.source))
  return <><PageHeader title="DNA Samples" subtitle={linkedPerson ? 'Samples linked to the selected missing person.' : role === 'Lab Technician' ? `DNA sample records assigned to ${assignedLab || 'your laboratory'}.` : 'DNA sample collection and analysis records.'} action={role === 'Officer' ? <Link to={`/dna-samples/new${linkedPerson ? `?personId=${linkedPerson}` : ''}`} className="btn btn-primary">Register DNA Sample</Link> : null}/><SearchFilters onSearchChange={setQuery} onClear={() => setFilters({ status: '', source: '' })}><Filter label="Analysis" value={filters.status} values={['Awaiting Analysis', 'Analyzed']} onChange={status => setFilters({ ...filters, status })}/><Filter label="Source" value={filters.source} values={['Missing Person', 'Family Member', 'Personal Belonging', 'Unidentified Remains']} onChange={source => setFilters({ ...filters, source })}/></SearchFilters><div className="card"><div className="table-responsive"><table className="table table-hover align-middle mb-0"><thead><tr><th>Sample ID</th><th>Source</th><th>Sample Type</th><th>Person / Family</th><th>Case</th><th>Lab</th><th>Collection Date</th><th>Analysis</th><th>Actions</th></tr></thead><tbody>{rows.map(item => <tr key={item.id}><td className="fw-semibold">{item.id}</td><td>{item.source}</td><td>{item.type}</td><td>{sampleOwner(item, data)}</td><td>{data.cases.find(caseItem => caseItem.id === item.caseId)?.id || '—'}</td><td>{item.lab}</td><td>{item.collected}</td><td><StatusBadge value={item.status}/></td><td className="text-nowrap"><TableAction to={`/dna-samples/${item.id}`}/>{role === 'Lab Technician' && item.status === 'Awaiting Analysis' && <Link className="btn btn-sm btn-primary ms-1" to={`/lab/analysis/${item.id}`}>Analyze</Link>}</td></tr>)}{!rows.length && <tr><td colSpan="9" className="text-center text-secondary py-4">No matching samples found.</td></tr>}</tbody></table></div></div></>
}

export function SampleForm() {
  const nav = useNavigate(); const [params] = useSearchParams(); const { data, addSample } = useData(); const [form, setForm] = useState({ source: '', personId: params.get('personId') || '', familyMemberId: '', caseId: '', lab: '', type: '', collected: '', storage: '', remarks: '' }); const change = event => { const next = { ...form, [event.target.name]: event.target.value }; if (event.target.name === 'personId') { next.familyMemberId = ''; next.caseId = data.cases.find(item => item.personId === event.target.value)?.id || '' } setForm(next) }; const personOptions = data.missingPeople.map(person => ({ value: person.id, label: `${person.id} — ${person.firstName} ${person.lastName}` })); const familyOptions = data.familyMembers.filter(member => member.personId === form.personId).map(member => ({ value: member.id, label: `${member.id} — ${member.name} (${member.relation})` })); const caseOptions = data.cases.filter(item => item.personId === form.personId).map(item => ({ value: item.id, label: item.id }))
  return <><PageHeader title="Register DNA Sample" subtitle="Record DNA source, provider, lab assignment, and related investigation case."/><form className="card" onSubmit={event => { event.preventDefault(); const record = addSample(form); nav(`/dna-samples/${record.id}`) }}><div className="card-body"><div className="row g-3"><Field label="DNA Source" name="source" select required value={form.source} onChange={change} options={['Missing Person', 'Family Member', 'Personal Belonging', 'Unidentified Remains']}/><Field label="Missing Person" name="personId" select required value={form.personId} onChange={change} options={personOptions}/>{form.source === 'Family Member' && <Field label="Family Member" name="familyMemberId" select required value={form.familyMemberId} onChange={change} options={familyOptions}/>}<Field label="Related Case" name="caseId" select required value={form.caseId} onChange={change} options={caseOptions}/><Field label="DNA Lab" name="lab" select required value={form.lab} onChange={change} options={data.labs.map(lab => lab.name)}/><Field label="Sample Type" name="type" select required value={form.type} onChange={change} options={['Buccal swab', 'Blood sample', 'Hair strand', 'Bone sample']}/><Field label="Collection Date" name="collected" type="date" required value={form.collected} onChange={change}/><Field label="Storage Location" name="storage" required value={form.storage} onChange={change}/><div className="col-12"><label className="form-label">Collection Remarks</label><textarea name="remarks" value={form.remarks} onChange={change} className="form-control" rows="4"/></div></div></div><div className="card-footer bg-white text-end"><Link to="/dna-samples" className="btn btn-light me-2">Cancel</Link><button className="btn btn-primary">Save DNA Sample</button></div></form></>
}

export function SampleDetails() {
  const { id } = useParams(); const { role, user } = useAuth(); const { data } = useData(); const sample = data.samples.find(item => item.id === id); if (!sample) return <NotFound label="DNA sample"/>; if (!labCanAccessSample(role, user, data, sample)) return <AccessDenied/>; const person = data.missingPeople.find(item => item.id === sample.personId); const member = sample.familyMemberId ? data.familyMembers.find(item => item.id === sample.familyMemberId) : null; const relatedCase = data.cases.find(item => item.id === sample.caseId)
  return <><PageHeader title={sample.id} subtitle="DNA sample record" action={role === 'Lab Technician' && sample.status === 'Awaiting Analysis' ? <Link className="btn btn-primary" to={`/lab/analysis/${sample.id}`}>Analyze Sample</Link> : null}/><div className="row g-4"><div className="col-lg-6"><Card title="Collection and relationship information"><div className="detail-grid"><span>DNA source<b>{sample.source}</b></span><span>Sample type<b>{sample.type}</b></span><span>Provider / owner<b>{sampleOwner(sample, data)}</b></span><span>Missing person<b>{person ? role === 'Lab Technician' ? `${person.firstName} ${person.lastName}` : <Link to={`/missing-persons/${person.id}`}>{person.firstName} {person.lastName}</Link> : '—'}</b></span><span>Family member<b>{member?.name || '—'}</b></span><span>Related case<b>{relatedCase ? role === 'Lab Technician' ? relatedCase.id : <Link to={`/cases/${relatedCase.id}`}>{relatedCase.id}</Link> : '—'}</b></span><span>Collection date<b>{sample.collected}</b></span><span>Storage location<b>{sample.storage}</b></span><span>Assigned laboratory<b>{sample.lab}</b></span></div></Card></div><div className="col-lg-6"><Card title="Analysis information"><div className="d-flex justify-content-between mb-3"><span>Current state</span><StatusBadge value={sample.status}/></div><div className="detail-grid"><span>Analysis date<b>{sample.analysis}</b></span><span>DNA profile code<b>{sample.profile}</b></span></div><hr/><b>Laboratory remarks</b><p className="mb-0 mt-1">{sample.remarks || '—'}</p></Card></div></div></>
}

export function DNAAnalysis() {
  const { id } = useParams(); const { data, updateSample } = useData(); const { user } = useAuth(); const sample = data.samples.find(item => item.id === id); const nav = useNavigate(); const [form, setForm] = useState({ analysis: '', profile: '', remarks: sample?.remarks || '' }); if (!sample) return <NotFound label="DNA sample"/>; if (sample.lab !== technicianLab(user, data)) return <AccessDenied/>; if (sample.status !== 'Awaiting Analysis') return <div className="alert alert-info">This sample has already been analyzed.</div>; const change = event => setForm({ ...form, [event.target.name]: event.target.value }); return <><PageHeader title={`Analyze ${sample.id}`} subtitle="Record analysis for this selected sample. Collection data remains read-only."/><div className="row g-4"><div className="col-lg-4"><Card title="Sample information"><p><span className="text-secondary d-block small">Source / provider</span>{sample.source} — {sampleOwner(sample, data)}</p><p><span className="text-secondary d-block small">Sample type</span>{sample.type}</p><p className="mb-0"><span className="text-secondary d-block small">Associated lab</span>{sample.lab}</p></Card></div><div className="col-lg-8"><form className="card" onSubmit={event => { event.preventDefault(); updateSample(sample.id, { ...form, status: 'Analyzed' }); nav(`/dna-samples/${sample.id}`) }}><div className="card-header bg-white"><strong>Analysis information</strong></div><div className="card-body"><div className="row g-3"><Field label="Analysis Date" name="analysis" type="date" required value={form.analysis} onChange={change}/><Field label="DNA Profile Code" name="profile" required value={form.profile} onChange={change}/><div className="col-12"><label className="form-label">Laboratory Remarks</label><textarea name="remarks" value={form.remarks} onChange={change} className="form-control" rows="6" required/></div></div></div><div className="card-footer bg-white text-end"><Link to={`/dna-samples/${sample.id}`} className="btn btn-light me-2">Cancel</Link><button className="btn btn-primary">Mark Analysis Complete</button></div></form></div></div></>
}

export function Matches() {
  const { data } = useData(); const { role, user } = useAuth(); const [params] = useSearchParams(); const linkedPerson = params.get('personId'); const [query, setQuery] = useState(''); const [filters, setFilters] = useState({ confidence: '', status: '' }); const personSamples = linkedPerson ? data.samples.filter(item => item.personId === linkedPerson).map(item => item.id) : []; const assignedLab = technicianLab(user, data); const rows = data.matches.filter(item => (!linkedPerson || personSamples.includes(item.unknown) || personSamples.includes(item.matched)) && (role !== 'Lab Technician' || item.lab === assignedLab) && search(item, query) && (!filters.confidence || item.confidence === filters.confidence) && (!filters.status || item.status === filters.status)); return <><PageHeader title="DNA Matches" subtitle={linkedPerson ? 'DNA comparison results tied to the selected missing person.' : 'DNA profile comparison results for authorized investigation review.'}/><SearchFilters onSearchChange={setQuery} onClear={() => setFilters({ confidence: '', status: '' })}><Filter label="Confidence" value={filters.confidence} values={['High', 'Medium', 'Low']} onChange={confidence => setFilters({ ...filters, confidence })}/><Filter label="Status" value={filters.status} values={['Pending Review', 'Reviewed']} onChange={status => setFilters({ ...filters, status })}/></SearchFilters><div className="card"><div className="table-responsive"><table className="table table-hover mb-0"><thead><tr><th>Match ID</th><th>Sample A / Provider</th><th>Sample B / Provider</th><th>Similarity</th><th>Confidence</th><th>Match Date</th><th>Status</th><th/></tr></thead><tbody>{rows.map(item => <tr key={item.id}><td className="fw-semibold">{item.id}</td><td>{describeSample(item.unknown, data)}</td><td>{describeSample(item.matched, data)}</td><td className="fw-bold">{item.similarity}</td><td><StatusBadge value={item.confidence}/></td><td>{item.date}</td><td><StatusBadge value={item.status}/></td><td><TableAction to={`/dna-matches/${item.id}`}/></td></tr>)}{!rows.length && <tr><td colSpan="8" className="text-center text-secondary py-4">No matching DNA comparisons found.</td></tr>}</tbody></table></div></div></>
}

export function MatchDetails() {
  const { id } = useParams(); const { data, updateMatch } = useData(); const { role, user } = useAuth(); const match = data.matches.find(item => item.id === id); if (!match) return <NotFound label="DNA match"/>; if (role === 'Lab Technician' && match.lab !== technicianLab(user, data)) return <AccessDenied/>; const first = data.samples.find(item => item.id === match.unknown); const second = data.samples.find(item => item.id === match.matched); const canReview = role === 'Officer' || role === 'Lab Technician'; const canOpenSample = sample => sample && labCanAccessSample(role, user, data, sample)
  return <><PageHeader title={match.id} subtitle="DNA match comparison result" action={canReview && match.status !== 'Reviewed' ? <button onClick={() => updateMatch(match.id, { status: 'Reviewed' })} className="btn btn-primary">Mark as Reviewed</button> : null}/><div className="match-hero card mb-4"><div className="card-body"><div><span className="eyebrow">SAMPLE A</span><h3>{match.unknown}</h3><small>{describeSample(match.unknown, data)}</small></div><div className="match-score"><b>{match.similarity}</b><span>Similarity</span><StatusBadge value={`${match.confidence} Confidence`}/></div><div className="text-lg-end"><span className="eyebrow">SAMPLE B</span><h3>{match.matched}</h3><small>{describeSample(match.matched, data)}</small></div></div></div><div className="row g-4"><div className="col-md-6"><Card title="Compared samples"><p>Sample A: {canOpenSample(first) ? <Link to={`/dna-samples/${first.id}`}>{first.id}</Link> : match.unknown} <b>— {first ? sampleOwner(first, data) : 'record unavailable'}</b></p><p className="mb-0">Sample B: {canOpenSample(second) ? <Link to={`/dna-samples/${second.id}`}>{second.id}</Link> : match.matched} <b>— {second ? sampleOwner(second, data) : 'record unavailable'}</b></p></Card></div><div className="col-md-6"><Card title="Match record"><p>Match date: <b>{match.date}</b></p><p>Confidence: <StatusBadge value={match.confidence}/></p><p className="mb-0">Status: <StatusBadge value={match.status}/></p></Card></div></div></>
}

function describeSample(id, data) { const sample = data.samples.find(item => item.id === id); return sample ? `${sample.id} — ${sampleOwner(sample, data)}` : `${id} — unavailable sample record` }
function Filter({ label, value, values, onChange }) { return <div className="col-md-2"><label className="form-label">{label}</label><select className="form-select" value={value} onChange={event => onChange(event.target.value)}><option value="">All {label.toLowerCase()}s</option>{values.map(item => <option key={item}>{item}</option>)}</select></div> }
function Card({ title, children }) { return <div className="card h-100"><div className="card-header bg-white"><strong>{title}</strong></div><div className="card-body">{children}</div></div> }
function NotFound({ label }) { return <div className="alert alert-warning">This {label} could not be found.</div> }
function AccessDenied() { return <div className="alert alert-danger">You are not authorized to access this laboratory record.</div> }
